### ISSUE TITLE
"main" in package.json points to invalid path

### ISSUE THREAD

**Issue by Jameskmonger** [JSONScript/jsonscript#1]
The `main` field on [line 5 of package.json](https://github.com/JSONScript/jsonscript/blob/master/package.json#L5) points to `index.js`. There is no `index.js` in the root of this project, so anyone trying to import the script will run into issues.

**Comment by epoberezkin** [comment]
There is no javascript code to consume from the package, only JSON schemas, instruction definitions and tests.
The interpreter for JSONScript is in [jsonscript-js](https://github.com/epoberezkin/jsonscript-js).
Probably `main` should be just removed. Or maybe it should point to some schema, not sure.
